---
neovim_become_admin: true
neovim_become_admin_user: root
neovim_become: true
neovim_become_user: "{{ lookup('env', 'USER') }}"

neovim_version: 0.11.4
neovim_sha256: 79e7e160f9505819a5e12f3d9366be94213f5309fb912ef4ef3af52df3982977
